import type { Transaction } from "./TransactionItem";

export const transactionsMOCK: Transaction[] = [
  {
    id: "1",
    type: "Credit",
    value: 100,
    date: "2021-10-10",
    from: "John Doe",
    to: "Jane Doe",
  },
  {
    id: "2",
    type: "Debit",
    value: 50,
    date: "2021-10-11",
    from: "Jane Doe",
    to: "John Doe",
  },
  {
    id: "3",
    type: "Credit",
    value: 200,
    date: "2021-10-12",
    from: "John Doe",
    to: "Jane Doe",
  },
  {
    id: "4",
    type: "Debit",
    value: 75,
    date: "2021-10-13",
    from: "Jane Doe",
    to: "John Doe",
  },
  {
    id: "5",
    type: "Credit",
    value: 150,
    date: "2021-10-14",
    from: "John Doe",
    to: "Jane Doe",
  },
  {
    id: "6",
    type: "Debit",
    value: 25,
    date: "2021-10-15",
    from: "Jane Doe",
    to: "John Doe",
  },
  {
    id: "7",
    type: "Credit",
    value: 300,
    date: "2021-10-16",
    from: "John Doe",
    to: "Jane Doe",
  },
  {
    id: "8",
    type: "Debit",
    value: 100,
    date: "2021-10-17",
    from: "Jane Doe",
    to: "John Doe",
  },
  {
    id: "9",
    type: "Credit",
    value: 250,
    date: "2021-10-18",
    from: "John Doe",
    to: "Jane Doe",
  },
  {
    id: "10",
    type: "Debit",
    value: 125,
    date: "2021-10-19",
    from: "Jane Doe",
    to: "John Doe",
  },
  {
    id: "11",
    type: "Credit",
    value: 350,
    date: "2021-10-19",
    from: "Jane Doe",
    to: "John Doe",
  },
  {
    id: "12",
    type: "Debit",
    value: 175,
    date: "2021-10-19",
    from: "John Doe",
    to: "Jane Doe",
  },
  {
    id: "13",
    type: "Credit",
    value: 400,
    date: "2021-10-19",
    from: "Jane Doe",
    to: "John Doe",
  },
  {
    id: "14",
    type: "Debit",
    value: 200,
    date: "2021-10-19",
    from: "John Doe",
    to: "Jane Doe",
  },
  {
    id: "15",
    type: "Credit",
    value: 450,
    date: "2021-10-19",
    from: "Jane Doe",
    to: "John Doe",
  },
  {
    id: "16",
    type: "Debit",
    value: 250,
    date: "2021-10-19",
    from: "John Doe",
    to: "Jane Doe",
  },
  {
    id: "17",
    type: "Credit",
    value: 500,
    date: "2021-10-19",
    from: "Jane Doe",
    to: "John Doe",
  },
  {
    id: "18",
    type: "Debit",
    value: 300,
    date: "2021-10-19",
    from: "John Doe",
    to: "Jane Doe",
  },
  {
    id: "19",
    type: "Credit",
    value: 550,
    date: "2021-10-19",
    from: "Jane Doe",
    to: "John Doe",
  },
  {
    id: "20",
    type: "Debit",
    value: 350,
    date: "2021-10-19",
    from: "John Doe",
    to: "Jane Doe",
  },
];
